apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greenops

resources:
  - 00-namespace.yaml
  - 01-configmap.yaml
  - 02-db-init-configmap.yaml
  - 03-secrets.example.yaml
  - 10-postgres.yaml
  - 11-redis.yaml
  - 20-auth-service.yaml
  - 21-metrics-service.yaml
  - 22-alert-service.yaml
  - 23-api-gateway.yaml
  - 24-frontend.yaml
  - 30-prometheus.yaml
  - 31-grafana.yaml
  - 40-ingress.yaml
  - 50-hpa.yaml
