require("dotenv").config();

const express = require("express");
const cors = require("cors");
const axios = require("axios");
const promClient = require("prom-client");
const pool = require("./db");

const app = express();
const register = new promClient.Registry();

promClient.collectDefaultMetrics({ register });

const alertsGenerated = new promClient.Counter({
  name: "greenops_alerts_generated_total",
  help: "Number of alerts generated by alert-service",
  labelNames: ["type", "severity"],
});
const httpRequests = new promClient.Counter({
  name: "greenops_alert_http_requests_total",
  help: "Total HTTP requests handled by alert-service",
  labelNames: ["method", "route", "status"],
});

register.registerMetric(alertsGenerated);
register.registerMetric(httpRequests);

const thresholds = {
  energyKw: Number(process.env.ENERGY_THRESHOLD_KW || 70),
  carbonGrams: Number(process.env.CARBON_THRESHOLD_GRAMS || 420),
  renewableMin: Number(process.env.RENEWABLE_MIN_PERCENTAGE || 45),
};

app.use(cors());
app.use(express.json());
app.use((req, res, next) => {
  res.on("finish", () => {
    httpRequests.inc({
      method: req.method,
      route: req.route?.path || req.path,
      status: res.statusCode,
    });
  });
  next();
});

function asyncHandler(handler) {
  return (req, res, next) => Promise.resolve(handler(req, res, next)).catch(next);
}

async function ensureSchema() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS alerts (
      id SERIAL PRIMARY KEY,
      type VARCHAR(80) NOT NULL,
      severity VARCHAR(30) NOT NULL,
      message TEXT NOT NULL,
      value NUMERIC(8, 2) NOT NULL,
      threshold NUMERIC(8, 2) NOT NULL,
      status VARCHAR(30) NOT NULL DEFAULT 'open',
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);
}

const schemaReady = ensureSchema();
schemaReady.catch((error) => {
  console.error("Alert schema initialization failed", error.message);
});

function mapAlert(row) {
  return {
    id: row.id,
    type: row.type,
    severity: row.severity,
    message: row.message,
    value: Number(row.value),
    threshold: Number(row.threshold),
    status: row.status,
    createdAt: row.created_at,
  };
}

function buildAlerts(metric) {
  const alerts = [];

  if (metric.kilowatts > thresholds.energyKw) {
    alerts.push({
      type: "energy",
      severity: "high",
      message: `${metric.site} depasse le seuil energetique`,
      value: metric.kilowatts,
      threshold: thresholds.energyKw,
    });
  }

  if (metric.carbonGrams > thresholds.carbonGrams) {
    alerts.push({
      type: "carbon",
      severity: "medium",
      message: `${metric.site} produit trop de CO2`,
      value: metric.carbonGrams,
      threshold: thresholds.carbonGrams,
    });
  }

  if (metric.renewablePercentage < thresholds.renewableMin) {
    alerts.push({
      type: "renewable",
      severity: "medium",
      message: `${metric.site} a une part renouvelable trop basse`,
      value: metric.renewablePercentage,
      threshold: thresholds.renewableMin,
    });
  }

  return alerts;
}

async function saveAlert(alert) {
  await schemaReady;
  const result = await pool.query(
    `
      INSERT INTO alerts(type, severity, message, value, threshold)
      VALUES($1, $2, $3, $4, $5)
      RETURNING *
    `,
    [alert.type, alert.severity, alert.message, alert.value, alert.threshold]
  );

  alertsGenerated.inc({ type: alert.type, severity: alert.severity });
  return mapAlert(result.rows[0]);
}

app.get("/health", (req, res) => {
  res.json({ service: "alert-service", status: "UP" });
});

app.get(
  "/ready",
  asyncHandler(async (req, res) => {
    await schemaReady;
    await pool.query("SELECT 1");
    res.json({ service: "alert-service", ready: true });
  })
);

app.get(
  "/metrics",
  asyncHandler(async (req, res) => {
    res.set("Content-Type", register.contentType);
    res.end(await register.metrics());
  })
);

app.post(
  "/alerts/evaluate",
  asyncHandler(async (req, res) => {
    await schemaReady;
    const metricsUrl = process.env.METRICS_SERVICE_URL || "http://metrics-service:3003";
    const response = await axios.get(`${metricsUrl}/energy/metrics/live`);
    const metric = response.data;
    const candidates = buildAlerts(metric);
    const alerts = [];

    for (const alert of candidates) {
      alerts.push(await saveAlert(alert));
    }

    res.status(alerts.length ? 201 : 200).json({
      metric,
      thresholds,
      alerts,
    });
  })
);

app.get(
  "/alerts",
  asyncHandler(async (req, res) => {
    await schemaReady;
    const result = await pool.query(`
      SELECT *
      FROM alerts
      WHERE status = 'open'
      ORDER BY created_at DESC
      LIMIT 20
    `);

    res.json(result.rows.map(mapAlert));
  })
);

app.get(
  "/alerts/history",
  asyncHandler(async (req, res) => {
    await schemaReady;
    const limit = Math.min(Number(req.query.limit || 50), 100);
    const result = await pool.query(
      `
        SELECT *
        FROM alerts
        ORDER BY created_at DESC
        LIMIT $1
      `,
      [limit]
    );

    res.json(result.rows.map(mapAlert));
  })
);

app.use((error, req, res, next) => {
  console.error(error);
  res.status(500).json({ error: error.message });
});

const PORT = Number(process.env.PORT || 3004);

app.listen(PORT, () => {
  console.log(`Alert service running on port ${PORT}`);
});
