{
 "title": "GreenOps Observability",
 "tags": [
  "greenops",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Disponibilite des services",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"api-gateway|auth-service|metrics-service|alert-service|prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Trafic API Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (route, status) (rate(greenops_gateway_http_requests_total[5m]))",
     "legendFormat": "{{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Memoire des microservices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"api-gateway|auth-service|metrics-service|alert-service\"}",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}